### ISSUE TITLE
Add comment for ipa when upload to firim

### ISSUE THREAD

**Issue by pujiaxin33** [whlsxl/firim#15]
![image](https://user-images.githubusercontent.com/12654640/48533568-03456d00-e8e0-11e8-8e3a-afe7cc711fbc.png)
The comment in red rectangle.

**Comment by pujiaxin33** [comment]
How can i add comment for ipa

**Comment by pujiaxin33** [comment]
i just try app_desc="some app desc info"
but it's not work, any question for me?

**Comment by whlsxl** [comment]
可以在`Deliverfile`文件里指定metadata的位置`metadata_path`。这个功能是fastlane的功能，相关文档在官网就有[deliver文档](https://docs.fastlane.tools/actions/deliver/)

**Comment by pujiaxin33** [comment]
@whlsxl 感谢你的回答。我的关键问题是上传给firim的时候，如何带上app描述。我查看了一下你介绍的“ Deliverfile”，并没有找到firim相关的，更多更多的是`App Store Connect`相关的。

**Comment by xwartz** [comment]
firim 可以传 `app_changelog` 字段

**Comment by pujiaxin33** [comment]
@xwartz 谢谢，亲测可用。之前在该仓库，到处都没有找到这个字段，不知道哪里有说明。我是不是遗漏哪里？还望指点一下

**Comment by xwartz** [comment]
@pujiaxin33   文档上没有说明，需要看一下源码

**Comment by pujiaxin33** [comment]
@xwartz thanks，对于普通使用者来说，还是文档最直观了。我自己翻了一下源码，也只找到过一个app_desc字段。谢谢了哈，以后会多看看源码的
