### ISSUE TITLE
Firim API Token(xxx) not correct

### ISSUE THREAD

**Issue by cao903775389** [whlsxl/firim#16]
firim addtoken 命令后面要直接跟token么，为什么我用keychain添加了token，用fastlane打包的时候读取到的那个token不是我设置上的呢

**Comment by whlsxl** [comment]
`token`的读取有个顺序，
https://github.com/whlsxl/firim#assgin-api-token
你先看看在这个路径上有没有其他配置

**Comment by cao903775389** [comment]
> `token`的读取有个顺序，
> https://github.com/whlsxl/firim#assgin-api-token
> 你先看看在这个路径上有没有其他配置

开始用keychain方式添加，读出来的token始终不对，感觉好像是我appID的账号密码，后面换成了添加环境变量之后才读取正确

**Comment by cao903775389** [comment]
对了，这个app icon的话，我看那个demo里Fastfile里的配置就一个firim，这个app icon会自动识别么，我这边每次传上去之后fir后台上显示不出来app的icon

**Comment by whlsxl** [comment]
@cao903775389 在`Firimfile` 里 添加`icon`项 为icon的路径，你试试可不可以，之前firim必须上传jpg，所以这里必须上传jpg的限制。
