### ISSUE TITLE
android apk 文件如何上传有事例吗？

### ISSUE THREAD

**Issue by OOMROO** [whlsxl/firim#17]
小白，用Firim( firim_api_token:"xxx") 报错  Firim API ERROR error_code: 100109

**Comment by whlsxl** [comment]
是在`Firimfile` 里吗？
在`Firimfile` 应该是`firim_api_token "KEY"` 没有冒号，

```
firim --apk [APK_PATH] --app_identifier [IDENTIFIER] --app_name "[NAME]" --app_version "[VERSION]" --app_build_version "[BUILD_VERSION]"
```

上传的命令应该类似这样，参数大部分都能配置到`Firimfile`文件里，参照这个文件https://github.com/whlsxl/firim/blob/master/lib/firim/options.rb

**Comment by whlsxl** [comment]
我没有apk，以上没有测试，如果有任何问题请留言！

**Comment by fqiao** [comment]
请问该问题如何处理？

**Comment by whlsxl** [comment]
> 请问该问题如何处理？

也是`100109`这个错误吗？

**Comment by xwartz** [comment]
事列

```
firim(
      gradle_file: "config.gradle",
      apk: "app/build/outputs/apk/release.apk",
      firim_api_token: "xxxxx",
      app_changelog: changelog
    )
```

**Comment by fqiao** [comment]
尽可能把参数给全就不会有问题了

**Comment by fqiao** [comment]
> 事列
> 
> ```
> firim(
>       gradle_file: "config.gradle",
>       apk: "app/build/outputs/apk/release.apk",
>       firim_api_token: "xxxxx",
>       app_changelog: changelog
>     )
> ```

尽可能把参数给全就不会有问题了

**Comment by fqiao** [comment]
> > 请问该问题如何处理？
> 
> 也是`100109`这个错误吗？

尽可能把参数给全就不会有问题了

**Comment by whlsxl** [comment]
> > > 请问该问题如何处理？
> > 
> > 
> > 也是`100109`这个错误吗？
> 
> 尽可能把参数给全就不会有问题了

可以参考下这个文件 https://github.com/whlsxl/firim/blob/master/lib/firim/options.rb
这里有所有可配置参数和说明。
