### ISSUE TITLE
Error setting value '~/Desktop/myapp_ipa/myapp.ipa' for option 'ipa'

### ISSUE THREAD

**Issue by vicky1221** [whlsxl/firim#18]
Error setting value '~/Desktop/myapp_ipa/myapp.ipa' for option 'ipa' 我自定义IPA路径到桌面，如果使用绝对路径是可以找到ipa文件的，但是如果用~通配符就不能找到路径，不知道这个该怎么解决

**Comment by whlsxl** [comment]
@vicky1221 使用通配符的意思是？

**Comment by whlsxl** [comment]
need more informations
