### ISSUE TITLE
how to show update info?

### ISSUE THREAD

**Issue by kaelinda** [whlsxl/firim#19]
how to show update info
i want to updaload updateInfo

**Comment by whlsxl** [comment]
Did you mean [this]( https://github.com/whlsxl/firim/blob/master/lib/firim/options.rb#L64)
All the options from `app_name` to `app_changelog` can upload to firim 

[这个么？]( https://github.com/whlsxl/firim/blob/master/lib/firim/options.rb#L64)
所有从`app_name`到`app_changelog` 的选项都可以被传到 `firim` 上
如果有疑问请打开这个issue
