### ISSUE TITLE
no implicit conversion of nil into String after update app info successed

### ISSUE THREAD

**Issue by mayifan** [whlsxl/firim#2]
TypeError: [!] no implicit conversion of nil into String
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/firim-0.1.1/lib/firim/runner.rb:46:in `initialize'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/firim-0.1.1/lib/firim/runner.rb:46:in `open'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/firim-0.1.1/lib/firim/runner.rb:46:in `write_app_info_to_file'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/firim-0.1.1/lib/firim/runner.rb:39:in `run'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-plugin-firim-0.1.0/lib/fastlane/plugin/firim/actions/firim_action.rb:8:in `run'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/runner.rb:227:in `block (2 levels) in execute_action'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/runner.rb:212:in `block in execute_action'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/runner.rb:211:in `chdir'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/runner.rb:211:in `execute_action'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/runner.rb:133:in `trigger_action_by_name'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:41:in `block (2 levels) in parsing_binding'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane_core-0.60.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
  /Users/mayifan/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.1.1/bin/fastlane:5:in `<top (required)>'
  /Users/mayifan/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
  /Users/mayifan/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<top (required)>'

**Comment by whlsxl** [comment]
@mayifan Thanks to commit this bug 
You can temporarily assign `app_info_to_file_path` in `Firimfile`
I'll fix this soon
