### ISSUE TITLE
Error setting value '/Users/guiming.zheng/Desktop/Projects/Clover_Dev/build/201911181456_1.3.0QA.ipa' for option 'ipa'

### ISSUE THREAD

**Issue by JoyHopes** [whlsxl/firim#21]
![image](https://user-images.githubusercontent.com/15683503/69032799-4917a280-0a18-11ea-9a34-c55c79de0fcf.png)
![截屏2019-11-18下午3 28 51](https://user-images.githubusercontent.com/15683503/69032818-4f0d8380-0a18-11ea-9b4b-458657b314af.png)

**Comment by JoyHopes** [comment]
Fastlane action parameters ipa setting is invalid, the error is IPA_OUTPUT_PATH, can someone help me see it?

**Comment by whlsxl** [comment]
上面的用法有两个问题，

1. `app_short` 应该是一个字符串，不能是整个链接，[文档](https://fir.im/docs/publish)。而且相同的`bundle_id`会被fir.im整理到一个应用里，这样上传会覆盖掉之前的版本，可行的做法是设置不同的配置文件，编译出不同的`bundle_id`，这样就不会冲突。
2. 用`ipa`指定文件位置，`file`参数是之前预留给另一个功能的。

**Comment by JoyHopes** [comment]
![image](https://user-images.githubusercontent.com/15683503/69112796-25a63380-0abc-11ea-97da-dcab93c0824b.png)
我仅仅zai在gym之后 把ipa包的名字 更换 然后设置一个新的ipa文件地址  还是报错 这个ipa指定文件失效
![image](https://user-images.githubusercontent.com/15683503/69112845-49697980-0abc-11ea-9e38-d06306a9626f.png)

**Comment by JoyHopes** [comment]
@whlsxl 因为ipa设置无效 我才试着设置一下file 我现在都尝试了 这个ipa 脚本一直使用的是gym编译出来的ipa文件路径 而不是我设置的那个

**Comment by whlsxl** [comment]
这里我没看明白，你的两个lane 应该是没有关系的。
我看你是执行了另一个`lane`。
新建个仓库，把配置文件都上传把，这样管中窥豹，实在不知道是什么意思。

**Comment by ZhengGuiMing** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.15.1                                      |
| Ruby                        | 2.7.0                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.21.0 (Apple Git-122.2)         |
| Installation Source         | ~/.rvm/gems/ruby-2.7.0-preview1/bin/fastlane |
| Host                        | Mac OS X 10.15.1 (19B88)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.0-preview1/lib        |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version               | 11.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform :ios

default_platform(:ios)

platform:ios do
     desc "fastlane Release版本"
     lane :Release_Unpiloted do
        # add actions here: https://docs.fastlane.tools/actions
        ENV["ENV_PARAM"] = "QA"
        ENV["CONFIGURATION_TYPE"] = "Release"
        ENV["MATCH_TYPE"] = "enterprise"
        ENV["MATCH_CERT"] = "iPhone Distribution: WM Motor Technology Co., Ltd."
        increment_Version_Info
        gym_WM
        # uploadToPgyer
        uploadToFirim
     end

    desc "增加build,只要编译就增加一次, 不能手动调用"
    lane :increment_Version_Info do
        version_number = get_version_number(target:"FastlaneTest")
        build_number = Time.new.strftime("%Y%m%d%H%M")
        
        increment_build_number build_number: build_number
        temVersion = version_number[-2,2]
        puts "-----temVersion:" + temVersion
        if temVersion.eql?("QA") || temVersion.eql?("PP")
                version_number = version_number[0,version_number.length - 2]
                puts "-----version_number:" + version_number
        end
        # QA 标示,方便crash分析
        # if ENV["ENV_PARAM"].eql?("Release")
        increment_version_number version_number: version_number
        exp_app_name = build_number + "_" + version_number + ENV["ENV_PARAM"]
        # else
        #     version_number = version_number + ENV["ENV_PARAM"]
        #     increment_version_number version_number: version_number
        #     exp_app_name = build_number + "_" + version_number
        # end
        
        ENV["APP_NAME"] = exp_app_name
        puts "----------- Version_INFO_START ---------------"
        puts "版本号:" + version_number
        puts "build号:" + build_number
        puts "ipa Name:" + exp_app_name + ".ipa"
        puts "----------- Version_INFO_END   ---------------"
    end

    desc "根据参数编译工程,不能直接调用"
    lane :gym_WM do
    gym(
        scheme: "FastlaneTest",
        # workspace: "Clover_UnpilotedDemo.xcworkspace",
        include_bitcode: false,
        output_name: ENV["APP_NAME"]+".ipa",
    #use_legacy_build_api:true,
        # configuration: "Release_QA",
        configuration: ENV["CONFIGURATION_TYPE"],
        codesigning_identity: ENV["MATCH_CERT"],
        export_method: ENV["MATCH_TYPE"],
        clean: true,
        output_directory: "build"
    )
    end


    desc "fir.im upload"
    lane :uploadToFirim do
        file = "./build/safa_"+ENV["APP_NAME"]+".ipa"
        file0 = "/Users/guiming.zheng/Desktop/Codes/19.10/FastlaneTest/build/"
        file1 =  file0+ENV["APP_NAME"]+".ipa"
        file2 =  file0+"safa_"+ENV["APP_NAME"]+".ipa"

        File.rename(file1,file2)

          # 上传ipa到fir.im服务器，在fir.im获取firim_api_token
        # firim(
        #     ipa: "./build/safa_201911181730_1.0QA.ipa",
            # firim_api_token: "ba2cad588fbff2582318060abceec297")

        fir_cli(api_token:"ba2cad588fbff2582318060abceec297",specify_file_path:"./build/safa_201911181730_1.0QA.ipa")
    end

end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.136.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status      |
| -------------------------- | ------- | ------------------ |
| fastlane-plugin-versioning | 0.4.0   | 🚫 Update available |
| fastlane-plugin-firim      | 0.2.0   | ✅ Up-To-Date       |
| fastlane-plugin-versioning | 0.4.0   | 🚫 Update available |
| fastlane-plugin-fir_cli    | 0.1.0   | 🚫 Update available |


<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.3.0        |
| slack-notifier             | 2.3.2        |
| atomos                     | 0.1.3        |
| CFPropertyList             | 3.0.1        |
| claide                     | 1.0.3        |
| colored2                   | 3.1.2        |
| nanaimo                    | 0.2.6        |
| xcodeproj                  | 1.13.0       |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| terminal-notifier          | 2.0.0        |
| unicode-display_width      | 1.6.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.5.0        |
| public_suffix              | 2.0.5        |
| addressable                | 2.7.0        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-screen                 | 0.7.0        |
| tty-cursor                 | 0.7.0        |
| tty-spinner                | 0.9.1        |
| babosa                     | 1.0.3        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| excon                      | 0.68.0       |
| faraday                    | 0.17.0       |
| unf_ext                    | 0.0.7.6      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20190701 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.13.1       |
| fastimage                  | 2.1.7        |
| gh_inspector               | 1.1.3        |
| json                       | 2.2.0        |
| mini_magick                | 4.9.5        |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.3.0        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| dotenv                     | 2.7.5        |
| naturally                  | 2.2.0        |
| simctl                     | 1.6.6        |
| jwt                        | 2.1.0        |
| uber                       | 0.1.0        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.2        |
| mime-types-data            | 3.2019.1009  |
| mime-types                 | 3.3          |
| multi_json                 | 1.14.1       |
| signet                     | 0.12.0       |
| memoist                    | 0.16.1       |
| os                         | 1.0.1        |
| googleauth                 | 0.6.7        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.23.9       |
| google-cloud-env           | 1.3.0        |
| google-cloud-core          | 1.4.1        |
| digest-crc                 | 0.4.1        |
| google-cloud-storage       | 1.16.0       |
| emoji_regex                | 1.0.1        |
| bundler                    | 2.1.0.pre.1  |
| forwardable                | 1.2.0        |
| logger                     | 1.3.0        |
| stringio                   | 0.0.2        |
| ipaddr                     | 1.2.2        |
| openssl                    | 2.1.2        |
| ostruct                    | 0.1.0        |
| strscan                    | 1.0.0        |
| date                       | 2.0.0        |
| fileutils                  | 1.1.0        |
| io-console                 | 0.4.7        |
| zlib                       | 1.0.0        |
| rexml                      | 3.1.9        |
| psych                      | 3.1.0        |
| mutex_m                    | 0.1.0        |
| fastlane-plugin-versioning | 0.4.0        |
| firim                      | 0.2.1        |
| fastlane-plugin-firim      | 0.2.0        |
| thor                       | 0.20.3       |
| http-accept                | 1.7.0        |
| netrc                      | 0.11.0       |
| rest-client                | 2.1.0        |
| ruby_android_apk           | 0.7.7.1      |
| chunky_png                 | 1.3.11       |
| rqrcode                    | 0.10.1       |
| api_tools                  | 0.1.0        |
| fir-cli                    | 1.7.4        |
| fastlane-plugin-fir_cli    | 0.1.0        |
</details>


*generated on:* **2019-11-21**
</details>

**Comment by JoyHopes** [comment]
截图的最上面很明显是gym执行之后的 导出符号表和ipa文件  怎么看出执行一个lane呢

单独走lane uploadToFirim  没有问题  先gym 后upload  如果action firim() 里把 ipa路径修改 就会报上述错误

如果再看不明白 那就关了吧。。

**Comment by JoyHopes** [comment]
![image](https://user-images.githubusercontent.com/15683503/69298924-384e7300-0c4a-11ea-93c8-211f45cce1bf.png)

**Comment by whlsxl** [comment]
已修复，可以升级试试。
