### ISSUE TITLE
firim upload success,but Firim Api error 100108 

### ISSUE THREAD

**Issue by JoyHopes** [whlsxl/firim#22]
![image](https://user-images.githubusercontent.com/15683503/69034463-3dc67600-0a1c-11ea-9a77-83dd38f5bbfb.png)

**Comment by whlsxl** [comment]
如果和https://github.com/whlsxl/firim/issues/21 是一个问题的话，有可能是`short`输入错误；如果不是，请提供下配置。
`firim`文档里没有错误代码，先看下是不是配置问题，如果不能解决，我问下`firim`

**Comment by whlsxl** [comment]
如果问题没有解决，欢迎重新打开
