### ISSUE TITLE
Can't set app password

### ISSUE THREAD

**Issue by devsaddle** [whlsxl/firim#23]
Unresolved conflict between options: 'app_is_show_plaza' and 'app_passwd'

**Comment by whlsxl** [comment]
这两个选项是有冲突么？
请问是怎么配置的？

**Comment by devsaddle** [comment]
![image](https://user-images.githubusercontent.com/11585911/71657320-5a273380-2d7a-11ea-9b33-fff3d20b55a0.png)

**Comment by devsaddle** [comment]
直接报错

**Comment by whlsxl** [comment]
这个问题是`fir.im` API的bug。
[文档](https://fir.im/docs/apps_edit)中说，`is_show_plaza`，`is_opened`，`passwd`是互相冲突的。
但是实际上，如果设置了`passwd`，必须同时把`is_opened`设置成`false`才能生效。
例如：
```
firim(firim_api_token: "***", ipa: "***",  app_passwd: "123456", app_is_opened: false)
```
`is_show_plaza`这个我不太清楚作用。
升级[0.2.3](https://rubygems.org/gems/firim/versions/0.2.3)取消冲突检测。
