### ISSUE TITLE
FastLine 中如何配置 **firim**

### ISSUE THREAD

**Issue by pengcao1** [whlsxl/firim#24]
```
      firim(firim_api_token: "#{APP_TOKEN}",
	      platform: ios,
	      app_changelog: "test for firm"
      )
```

提示如下错误

> Could not find action, lane or variable 'ios'. Check out the documentation for more details:

**Comment by whlsxl** [comment]
```
      firim(firim_api_token: "#{APP_TOKEN}",
	      platform: "ios",
	      app_changelog: "test for firm"
      )
```
是不是忘了加引号

**Comment by whlsxl** [comment]
我先关闭了，再有问题欢迎打开

**Comment by xwartz** [comment]
fir 这个网站被关闭了 http://fir.im/，切换到 http://www.jappstore.com/ 了 😅

**Comment by whlsxl** [comment]
我看看发生了什么🤔

**Comment by whlsxl** [comment]
@xwartz 
`fir.im` API在qiniu那面的回调，还是`fir.im`的域名，回调失败，这就得等官方修复了。
有没有联系官方的渠道？

**Comment by xwartz** [comment]
只能通过发邮件 help@fir.im 联系，但我估计邮箱已经爆炸了，网站停了 2 天了..

**Comment by whlsxl** [comment]
> 只能通过发邮件 [help@fir.im](mailto:help@fir.im) 联系，但我估计邮箱已经爆炸了，网站停了 2 天了..

已发邮件，更新了可以设置URL，但是在官方修复之前，是用不了的。

**Comment by whlsxl** [comment]
> > 只能通过发邮件 [help@fir.im](mailto:help@fir.im) 联系，但我估计邮箱已经爆炸了，网站停了 2 天了..
> 
> 已发邮件，更新了可以设置URL，但是在官方修复之前，是用不了的。

官方已修复

**Comment by xwartz** [comment]
下午试过了，已经 OK
