### ISSUE TITLE
建议更新到临时域名

### ISSUE THREAD

**Issue by iTofu** [whlsxl/firim#25]
fir.im 挂了三天了，不如先更新到他们的临时域名 jappstore.com，以便开发者继续使用脚本发布应用

**Comment by iTofu** [comment]
@whlsxl

**Comment by xwartz** [comment]
更新到最新版本，可以传参，https://github.com/whlsxl/firim/commit/f36dbfb2912b2e5f8b753b0472f764cab3c0384f

**Comment by iTofu** [comment]
干得漂亮
