### ISSUE TITLE
fir.im 域名更改导致的插件会出现的问题

### ISSUE THREAD

**Issue by jicheng1014** [whlsxl/firim#26]
大佬您好   

因为 fir.im 的备案被吊销, 可能对您这个插件有很大影响

目前 接口 api.fir.im  已经切换到了  api.bq04.com 接口方法不变

另外 fir.im 上传方式 默认从七牛 切换到了 ali  需要手动 callback 下  不知是否对您这有影响

**Comment by whlsxl** [comment]
终于对上线了～
callback 的部分，现在有文档吗？

**Comment by whlsxl** [comment]
https://www.betaqr.com/docs/publish
文档里目前还是qiniu的接口

**Comment by jicheng1014** [comment]
回头我改改吧   现在在忙着救火  😆       
要不您先参看下 

https://github.com/FIRHQ/fir-cli/blob/e8d0b67963878c80067a0ee58d5b54a7d7c22e62/lib/fir/util/app_uploader.rb#L23

**Comment by whlsxl** [comment]
OK

**Comment by whlsxl** [comment]
目前配置中的`firim_api_url`改为`https://api.jappstore.com/`或`https://api.bq04.com` 均可用

**Comment by jicheng1014** [comment]
感谢修复~

**Comment by whlsxl** [comment]
@jicheng1014 
请问现在域名稳定在`https://api.bq04.com/`了吗？

**Comment by jicheng1014** [comment]
官方维护的api  目前有 
fir-api.fircli.cn 和 api.bq04.com

其中 fir-api.fircli.cn 为 web 默认的api

**Comment by xwartz** [comment]
@whlsxl 应该用 https 的吧，描述上有问题

**Comment by whlsxl** [comment]
> @whlsxl 应该用 https 的吧，描述上有问题

已修复
