### ISSUE TITLE
钉钉安全选项支持

### ISSUE THREAD

**Issue by beijiahiddink** [whlsxl/firim#28]
现在钉钉机器人必须选择安全选项，请支持一下

**Comment by whlsxl** [comment]
> 现在钉钉机器人必须选择安全选项，请支持一下

不太明白这个意思，能再具体描述下么？

**Comment by beijiahiddink** [comment]
就是现在创建钉钉机器人必须要选择他的安全选项，只有token貌似没有办法发送提醒给钉钉

**Comment by beijiahiddink** [comment]
> > 现在钉钉机器人必须选择安全选项，请支持一下
> 
> 不太明白这个意思，能再具体描述下么？
就是现在创建钉钉机器人必须要选择他的安全选项，只有token貌似没有办法发送提醒给钉钉

**Comment by beijiahiddink** [comment]
> > 现在钉钉机器人必须选择安全选项，请支持一下
> 
> 不太明白这个意思，能再具体描述下么？

就是现在创建钉钉机器人必须要选择他的安全选项，只有token貌似没有办法发送提醒给钉钉

**Comment by whlsxl** [comment]
这个貌似不是firim 的功能吧，你是通过什么实现和钉钉通讯的？

**Comment by whlsxl** [comment]
抱歉，我不用钉钉，最好有些链接之类的，我参考下。
