### ISSUE TITLE
fastlane finished with errors

### ISSUE THREAD

**Issue by SunQiDreamer** [whlsxl/firim#29]
[!] Response body ERROR: <html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

**Comment by whlsxl** [comment]
刚才测试了下，目前firim插件没有问题
检查下有没有设置`URL` https://github.com/whlsxl/firim/issues/26#issuecomment-593854518
有没有更新最新的firim

**Comment by SunQiDreamer** [comment]
> 刚才测试了下，目前firim插件没有问题
> 检查下有没有设置`URL` [#26 (comment)](https://github.com/whlsxl/firim/issues/26#issuecomment-593854518)
> 有没有更新最新的firim

搞定了，fir域名改了，哈哈
