### ISSUE TITLE
fastlane 2.147.0 版本报依赖冲突

### ISSUE THREAD

**Issue by akring** [whlsxl/firim#30]
报错信息：

> Error loading plugin 'fastlane-plugin-firim': Unable to activate firim-0.2.4, because faraday-1.0.1 conflicts with faraday (~> 0.9), faraday_middleware-1.0.0 conflicts with faraday_middleware (~> 0.9)

Ruby 版本：ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

Fastlane 版本：2.147.0

看作者是否考虑更新一下 faraday 的依赖版本

**Comment by whlsxl** [comment]
fixed: a1fa76e40315537cda0a87730c6ea5d9ed6045c0

**Comment by whlsxl** [comment]
请升级0.2.5
https://rubygems.org/gems/firim
