### ISSUE TITLE
获取下载地址

### ISSUE THREAD

**Issue by lovelinxue** [whlsxl/firim#32]
想知道使用fastlane 打包好并上传到fir之后,   有打印一个APP info 的信息.   我想上传成功之后,直接打印出来下载地址...   但是不知道这个参数怎么获取, short和download_domain

**Comment by whlsxl** [comment]
是有下载地址的啊
![image](https://user-images.githubusercontent.com/305995/102798929-bdc3ca00-43ec-11eb-9c79-fbddf3d04685.png)

**Comment by whlsxl** [comment]
由于官方API没有提供打印下载地址的字段，这个字段是我拼上的。
规则就是 `http://d.firim.top/#{short}`， 这里的`short`用的是接口返回的，不用设置。
如果绑定了自己的域名，请设置`download_page_prefix`，生成的规则是`#{download_page_prefix}#{short}`。
在终端中显示的字段是`download_page_url`

**Comment by XmYhkj** [comment]
请问我在调用了firim之后如何取出这两个参数#{download_page_prefix}#{short}？
我们的脚本需要自动发出通知，带上这个地址。
[16:22:11]: Could not find action, lane or variable 'download_page_prefix'. Check out the documentation for more details: https://docs.fastlane.tools/actions
@whlsxl

**Comment by whlsxl** [comment]
> 请问我在调用了firim之后如何取出这两个参数#{download_page_prefix}#{short}？
> 我们的脚本需要自动发出通知，带上这个地址。
> [16:22:11]: Could not find action, lane or variable 'download_page_prefix'. Check out the documentation for more details: https://docs.fastlane.tools/actions
> @whlsxl

需要怎么取出？

**Comment by whlsxl** [comment]
> 请问我在调用了firim之后如何取出这两个参数#{download_page_prefix}#{short}？ 我们的脚本需要自动发出通知，带上这个地址。 [16:22:11]: Could not find action, lane or variable 'download_page_prefix'. Check out the documentation for more details: https://docs.fastlane.tools/actions @whlsxl

我做了个环境变量导出，不知道符不符合你的需求。[README.md](https://github.com/whlsxl/firim#export-environments)

如果要在fastlane 里request 一个URL，可以用 [upload_to_server](http://docs.fastlane.tools/plugins/available-plugins/#upload_to_server) 这个插件。在ruby里使用环境变量可以直接获取`ENV["FIRIM_APP_URL"]`。
