### ISSUE TITLE
firm报错100108

### ISSUE THREAD

**Issue by wzw110110** [whlsxl/firim#33]
![截屏2021-07-22 上午11 40 18](https://user-images.githubusercontent.com/19481570/126587145-87367518-2f27-4649-9a83-7ea75fa88ed7.png)
打包完之后,app_short没有生效
麻烦帮忙看下，非常感谢

**Comment by whlsxl** [comment]
[http://d.firim.top/kwtest](http://d.firim.top/kwtest)
应该 app_short 冲突，这个应用不是你们的吧。

**Comment by wzw110110** [comment]
> http://d.firim.top/kwtest
> 应该 app_short 冲突，这个应用不是你们的吧。

**Comment by wzw110110** [comment]
感谢老哥，是冲突的问题
