### ISSUE TITLE
可以将master_release_id输出到env中吗

### ISSUE THREAD

**Issue by lee409** [whlsxl/firim#34]
可以将master_release_id输出到env中吗

**Comment by whlsxl** [comment]
没明白，这个是要输出什么内容啊？

**Comment by lee409** [comment]
发布到app后我需要将预览地址通过webhook分发到钉钉。预览地址格式是http://d.firim.pro/xxxxx?release_id=6xxxxxxx6
http://d.firim.pro/xxxxx你源码中已经输出到FIRIM_APP_URL
release_id=6xxxxxxx6就是app_info里面的master_release_id，这个源码没有输出到env

**Comment by whlsxl** [comment]
环境变量`FIRIM_MASTER_RELEASE_ID`
https://github.com/whlsxl/firim/blob/master/README.md#export-environments

**Comment by whlsxl** [comment]
导出了其他的app info，https://github.com/whlsxl/firim#export-environments
https://github.com/whlsxl/firim/releases/tag/0.2.9
