### ISSUE TITLE
can't deliver ipa

### ISSUE THREAD

**Issue by gongyucheng** [whlsxl/firim#8]
`upload_binary_and_icon': [!] undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by whlsxl** [comment]
@gongyucheng I didn't got this error for now , even I create a new project. 
Print the detail of the error pls, THX.

**Comment by zhengyaoyuan** [comment]
Here is the detail. Could you help me?
[15:24:34]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `fetch' for nil:NilClass (NoMethodError) at send app submission (ITC)
    https://github.com/fastlane/fastlane/issues/12563 [open] 1 💬
    2 days ago

➡️  undefined method `map' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/12587 [closed] 1 💬
    a day ago

➡️  undefined method `in_house?' for nil:NilClass with fastlane 2.92
    https://github.com/fastlane/fastlane/issues/12327 [closed] 15 💬
    5 weeks ago

and 337 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.3.0/gems/firim-0.2.0/lib/firim/runner.rb:103:in `upload_binary_and_icon': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/firim-0.2.0/lib/firim/runner.rb:61:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-plugin-firim-0.2.0/lib/fastlane/plugin/firim/actions/firim_action.rb:10:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:23:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.96.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by whlsxl** [comment]
@zhengyaoyuan I think this is a server error, can you check the if the config is correct?

**Comment by whlsxl** [comment]
@zhengyaoyuan use new version of firim can get more detail log

**Comment by vicky1221** [comment]
这个应该是ruby语法错误，我今天刚遇到
